// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGSAEP3_bBGLuLYqAQtjRV1rq_XQtROFk',
    appId: '1:716575547527:web:6c50069aa82fdb979bd822',
    messagingSenderId: '716575547527',
    projectId: 'mastercard-6e3c9',
    authDomain: 'mastercard-6e3c9.firebaseapp.com',
    storageBucket: 'mastercard-6e3c9.firebasestorage.app',
    measurementId: 'G-CJEP1BT9K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5sMkKEMjpsq3_NY8lJnVepcxYgcGaVHI',
    appId: '1:716575547527:android:65bda7b6f72d1ebb9bd822',
    messagingSenderId: '716575547527',
    projectId: 'mastercard-6e3c9',
    storageBucket: 'mastercard-6e3c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrgTehPF0nJz9t1EHdQ_SccCtqlFbo7cs',
    appId: '1:716575547527:ios:1ce327b3a2db6dbf9bd822',
    messagingSenderId: '716575547527',
    projectId: 'mastercard-6e3c9',
    storageBucket: 'mastercard-6e3c9.firebasestorage.app',
    iosBundleId: 'com.example.cardMaster',
  );
}
